
server:
  port: 30002

config:
  # read all log files that has format of .txt
  dir-path: /Users/Documents/file/log

  # read json files that has multiple values for each field.
  # Then, read random value for each field and create log text.
  custom-log-path: /Users/Documents/file/customLog

  servers:
    - ip: 127.0.0.1
      port: 20001
      protocol: TCP

    - ip: 127.0.0.1
      port: 20002
      protocol: UDP
